import unittest
from src.guest import Guest

class TestGuest(unittest.TestCase):

    def setUp(self):
        self.guest1 = Guest(50, "Pop", "I See Fire")
        self.guest2 = Guest(50, "Pop", "I See Fire")
        self.guest3 = Guest(50, "Pop", "Girls Just Wanna Have Fun")
        self.guest4 = Guest(50, "Pop", "The Locomotion")
        self.guest5 = Guest(50, "Pop", "Four Minutes")
        self.guest6 = Guest(100, "Pop", "I Want It That Way")
        self.guest7 = Guest(100, "Pop", "It's Raining Men")
        self.guest8 = Guest(100, "Pop", "We Are Family")
        self.guest9 = Guest(100, "Pop", "Proud Mary")
        self.guest10 = Guest(100, "Pop", "Millenium")

        self.guest11 = Guest(100, "Pop", "No Matter What")
        self.guest12 = Guest(100, "Pop", "No Matter What")
        self.guest13 = Guest(100, "Pop", "Crazy Little Thing Called Love")
        self.guest14 = Guest(100, "Pop", "House of the Rising Sun")
        self.guest15 = Guest(100, "Pop", "The Number of the Beast")
        self.guest16 = Guest(200, "Pop", "Somebody to Love")
        self.guest17 = Guest(200, "Pop", "Like a Virgin")
        self.guest18 = Guest(200, "Pop", "Love Me Do")
        self.guest19 = Guest(200, "Pop", "Hey Jude")
        self.guest20 = Guest(200, "Pop", "Gin and Juice")

        self.guest21 = Guest(100, "Blues and Soul", "House of the Rising Sun")
        self.guest22 = Guest(100, "Blues and Soul", "House of the Rising Sun")
        self.guest23 = Guest(100, "Blues and Soul", "Crazy Little Thing Called Love")
        self.guest24 = Guest(100, "Blues and Soul", "House of the Rising Sun")
        self.guest25 = Guest(100, "Blues and Soul", "Roadrunner")
        self.guest26 = Guest(300, "Blues and Soul", "Bright Lights, Big City")
        self.guest27 = Guest(300, "Blues and Soul", "Birthday")
        self.guest28 = Guest(300, "Blues and Soul", "Happiness is a Warm Gun")
        self.guest29 = Guest(300, "Blues and Soul", "Lonely Boy")
        self.guest30 = Guest(300, "Blues and Soul", "Mannish Boy")

        self.guest31 = Guest(50, "Rock", "Vicious")
        self.guest32 = Guest(50, "Rock", "Vicious")
        self.guest33 = Guest(50, "Rock", "Vicious")
        self.guest34 = Guest(50, "Rock", "Burnout")
        self.guest35 = Guest(50, "Rock", "When I Come Around")
        self.guest36 = Guest(100, "Rock", "Welcome to Paradise")
        self.guest37 = Guest(100, "Rock", "T.N.T.")
        self.guest38 = Guest(100, "Rock", "Thunder")
        self.guest39 = Guest(100, "Rock", "Back in Black")
        self.guest40 = Guest(100, "Rock", "Paradise by the Dashboard Light")

        self.guest41 = Guest(100, "Metal", "The Number of the Beast")
        self.guest42 = Guest(100, "Metal", "The Number of the Beast")
        self.guest43 = Guest(100, "Metal", "Helter Skelter")
        self.guest44 = Guest(100, "Metal", "Tame")
        self.guest45 = Guest(100, "Metal", "Wave of Mutilation")
        self.guest46 = Guest(200, "Metal", "This Monkey's Going to Heaven")
        self.guest47 = Guest(200, "Metal", "Duality")
        self.guest48 = Guest(200, "Metal", "Run to the Hills")
        self.guest49 = Guest(200, "Metal", "Paranoid")
        self.guest50 = Guest(200, "Metal", "War Pigs")

        self.guest51 = Guest(100, "Country", "A Boy Named Sue")
        self.guest52 = Guest(100, "Country", "A Boy Named Sue")
        self.guest53 = Guest(100, "Country", "If I Were a Carpenter")
        self.guest54 = Guest(100, "Country", "House of the Rising Sun")
        self.guest55 = Guest(100, "Country", "The Number of the Beast")
        self.guest56 = Guest(200, "Country", "Sixteen Tons")
        self.guest57 = Guest(200, "Country", "No Matter What")
        self.guest58 = Guest(200, "Country", "Blue Train")
        self.guest59 = Guest(200, "Country", "The Day Fingerpickers Took Over the World")
        self.guest60 = Guest(200, "Country", "Bolsarino")

    
